### ISSUE TITLE
Not getting it to pickup source

### ISSUE THREAD

**Issue by wicadmin** [jefferyto/openwrt-vivarium#1]
Hi.
I created the package directory by cloning 18.06.5 packages. I then created a folder in packages called luci with subdirectories proto/Makefile. However is it not picking it up.

**Comment by wicadmin** [comment]
UPDATE: I got it to work except for one package which is in luci. How to specify where openwrt/luci packages are?

**Comment by jefferyto** [comment]
I'm not sure I understand what you are trying to do. Are you trying to add a custom package (in luci/proto)? What is the content of the Makefile?

**Comment by wicadmin** [comment]
sorry - I did get it to work. placing it in packages as documented worked. I started over and followed the directions better.
