### ISSUE TITLE
How to change to musl instead of glibc?

### ISSUE THREAD

**Issue by wicadmin** [jefferyto/openwrt-vivarium#3]
It seems these are being built with glibc and therefore issues using it as a repo in imagebuilder. How to change to musl?

**Comment by jefferyto** [comment]
Which C library is used depends on which SDK you selected (e.g. for 18.06, ar71xx-generic uses musl, arc770-generic uses uClibc). I don't believe any use glibc by default.

Please check to see you are using the correct [configuration options](https://github.com/jefferyto/openwrt-vivarium#configuration) (in particular the image build options).
