### ISSUE TITLE
TARGET_CFLAGS - How to enable?

### ISSUE THREAD

**Issue by wicadmin** [jefferyto/openwrt-vivarium#6]
Would like to enable debugging but when I place TARGET_CFLAGS in the Makefile, it doesn't pick up. Is there another place to put it?

In Makefile:
```
TARGET_CFLAGS += -ggdb3
```
Compile:
```
docker-compose run --rm builder make package/modemmanager/{clean,compile} -j2 V=s CONFIG_DEBUG=y CONFIG_TARGET_OPTIMIZATION="-O0"

```

**Comment by jefferyto** [comment]
I think you need to disable stripping as well (`CONFIG_NO_STRIP=y`).

**Comment by wicadmin** [comment]
ok, thanks....will try that.
