### ISSUE TITLE
How to use diffconfig

### ISSUE THREAD

**Issue by wicadmin** [jefferyto/openwrt-vivarium#7]
Hi - still using this project and it works great.

I would like to build some kernel modules and would like to know how to have them selected via diffconfig. Specifically these two (gobinet and gobiserial):

![image](https://user-images.githubusercontent.com/4563854/93001974-38816d00-f501-11ea-81ea-7a5b11c55487.png)

Thanks.

**Comment by jefferyto** [comment]
All [kmod packages](https://github.com/openwrt/openwrt/blob/0830ae3a2fdf444380153d311a7de167b92a68af/target/sdk/files/Config.in#L9-L11) (as well as all other packages) should be selected by default when building with the SDK.

If you include a partial config in `sdk/overrides/diffconfig`, it will be included in the config used by make, e.g.:

```
CONFIG_PACKAGE_kmod-gobinet=m
CONFIG_PACKAGE_kmod-gobiserial=m
```

I wasn't able to find these two packages in the main OpenWrt repo though, so I don't know if they will actually compile.

**Comment by jefferyto** [comment]
Closing due to age / lack or response.
