### ISSUE TITLE
Can this project patch kernel?

### ISSUE THREAD

**Issue by wicadmin** [jefferyto/openwrt-vivarium#9]
Would like to build the kernel to support MPTCP and wondering if this project can be used to apply the patches to the snapshot kernel sources?

**Comment by jefferyto** [comment]
I haven't tested this, but I believe you can:

1.  Clone the main OpenWrt repo to a directory inside the vivarium directory, e.g. `base`, and add your patches in here
2.  Add a line in `docker-compose.yml` under `volumes` to map `base` into the Docker container, e.g.:

    ```yaml
    volumes:
      - "./base:/home/build/openwrt_base"
    ```

3.  Add a custom `feeds.conf` in `sdk/overrides`, e.g.:

    ```
    src-link base /home/build/openwrt_base
    src-link packages /home/build/openwrt_packages
    src-git luci https://github.com/openwrt/luci.git;master
    ```

**Comment by wicadmin** [comment]
Thanks. I think the challenge will be how to then get that into image builder and does it required the corresponding kmod-* files too?

e.g.:
those found here `bin/targets/x86/64/packages`

![image](https://user-images.githubusercontent.com/4563854/116940612-327cff80-ac3c-11eb-971e-57a0fa2d21fc.png)

**Comment by jefferyto** [comment]
I believe local package files can be included by the Image Builder, but it may not be advisable to mix locally compiled kernel packages with the pre-built kernel from the base repo.

Closing as this is beyond the scope of this project.
